# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13wZZ7Nlqr7Ak0x2l9Mp3qyPK7Szirb90
"""

import numpy as np

# Example data (replace with actual data)
EnergyPerC = np.array([1.2, 0.9, 1.5, 1.0])
EnergyPerT = np.array([0.8, 1.1, 0.7, 1.3])
EnergyPerR = np.array([1.0, 1.0, 1.0, 1.0])
TimePerC = np.array([10.5, 10.7, 10.4, 10.8,1,1,0.1,0.2,0.3,0.3,0.5])

# Previous coefficients
alpha = 25.0
beta = 25.0
gamma = 25.0
delta = 25.0

# Learning rate
eta = 0.01

# Number of iterations
iterations = 10


# Gradient Descent with Projection
for _ in range(iterations):
    # Compute the gradients
    grad_alpha = np.mean(EnergyPerC)
    grad_beta = np.mean(EnergyPerT)
    grad_gamma = np.mean(EnergyPerR)
    grad_delta = np.mean(TimePerC)
    #print ("grad_alpha" , f"{grad_alpha}")
    #print ("grad_beta" , f"{grad_beta}")
    #print ("grad_gamma" , f"{grad_gamma}")
    print ("grad_delta" , f"{grad_delta}")

    # Update the coefficients
    alpha += eta * grad_alpha
    beta += eta * grad_beta
    gamma += eta * grad_gamma
    delta += eta * grad_delta
    #print ("alpha" , f"{alpha}")
    #print ("beta" , f"{beta}")
    #print ("gamma" , f"{gamma}")
    print ("delta" , f"{delta}")

    # Project the coefficients to the range [0, 100]
    alpha = max(0, min(100, alpha))
    beta = max(0, min(100, beta))
    gamma = max(0, min(100, gamma))
    delta = max(0, min(100, delta))

    # Output the optimized coefficients
    # print(f'Optimized alpha: {alpha}')
    # print(f'Optimized beta: {beta}')
    # print(f'Optimized gamma: {gamma}')
    # print(f'Optimized delta: {delta}')