NO_SENSORS = 20
SENSOR_MAX_POWER_MEAN = 0.35
SENSOR_MAX_POWER_STD_DEVIATION = 0
SENSOR_STATIC_POWER_MEAN = 0.007
SENSOR_STATIC_POWER_STD_DEVIATION = 0 #0.001
SENSOR_CU_POWER_MEAN = 10
SENSOR_CU_STD_DEVIATION = 2 #2
SENSOR_INITIAL_POWER_MEAN = 10
SENSOR_REMAINING_POWER_MEAN = SENSOR_INITIAL_POWER_MEAN

MICROPROCESSORS_POWER_RAM = 0.000212866
MICROPROCESSORS_MAX_POWER_MEAN = 0.36 #6.5
MICROPROCESSORS_MAX_POWER_STD_DEVIATION = 0.1 #1.5
MICROPROCESSORS_STATIC_POWER_MEAN = 0.1 #4.8
MICROPROCESSORS_STATIC_POWER_STD_DEVIATION = 0.01 #1
MICROPROCESSORS_CU_POWER_MEAN = 1100 #6000
MICROPROCESSORS_CU_STD_DEVIATION = 300 #100
MICROPROCESSORS_INITIAL_POWER_MEAN = 1000
MICROPROCESSORS_REMAINING_POWER_MEAN = MICROPROCESSORS_INITIAL_POWER_MEAN

SERVER_POWER_PER_CU = 20e-3
SERVER_STATIC_POWER = 100

SENSOR_TO_FOG_LINK_BANDWIDTH = 50e6
WIRED_BANDWIDTH_STD_DEVIATION = 10e6
SENSOR_TO_FOG_LINK_ENERGY_PER_BIT = 400e-9
WIRED_ENERGY_PER_BIT_STD_DEVIATION = 50e-9

FOG_TO_CLOUD_LINK_BANDWIDTH = 30e6
WIRELESS_BANDWIDTH_STD_DEVIATION = 5e5
FOG_TO_CLOUD_LINK_ENERGY_PER_BIT = 400e-9
WIRELESS_ENERGY_PER_BIT_STD_DEVIATION = 50e-9

TASK_MEAN= 600
TASK_STD_DEVIATION= 100

NUMBER_OF_FOGS=4